#!/usr/sbin/nft -f

flush ruleset
table inet filter {

set trusted_ips {
    type ipv4_addr;
    flags interval;
    elements = {
        178.150.69.156, 95.216.229.41, 193.123.36.107, 129.151.237.120, 95.217.87.245, 192.168.18.0/24,
        62.80.161.178, 94.130.143.81, 116.202.209.243, 168.119.212.183, 138.201.250.74, 195.201.9.226,
        194.62.137.238, 212.26.133.106, 37.187.95.231, 212.26.135.6, 65.21.29.93
    }
}

	chain input {
                type filter hook input priority filter; policy drop;

                # 🔒 Защита от пустых TCP-пакетов (NULL scan и др.)
                tcp flags & (fin|syn|rst|psh|ack|urg) == 0 counter drop comment "Drop malformed TCP packets"

                # ❌ Отбросить недопустимые соединения
                ct state invalid counter drop comment "Drop invalid connections"

                # ✅ Разрешить установленные и связанные соединения
                ct state established,related accept comment "Accept established and related connections"

                # ✅ Разрешить loopback
                iifname "lo" counter accept comment "Accept loopback interface"

				# ✅ Доступ с доверенных IP:
				ip saddr @trusted_ips  tcp dport { 22, 8006 } counter accept comment "My IP"
				ip saddr @trusted_ips  ip protocol icmp accept comment "My IP"

        }

	chain forward {
                type filter hook forward priority filter; policy drop;
                ct state invalid counter drop
                ct state established,related  accept
                iifname "vmbr1" oifname "vmbr0"  accept comment "Lan -> WAN"
		udp dport 49852	 accept
		ip saddr @trusted_ips tcp dport { 22, 8007, 10050 } counter accept

        }
}

table ip nat {

set trusted_ips_nat {
    type ipv4_addr;
    flags interval;

    elements = {
        178.150.69.156, 95.216.229.41, 193.123.36.107, 129.151.237.120, 95.217.87.245, 192.168.18.0/24,
        62.80.161.178, 94.130.143.81, 116.202.209.243, 168.119.212.183, 138.201.250.74, 195.201.9.226,
        194.62.137.238, 212.26.133.106, 37.187.95.231, 212.26.135.6, 65.21.29.93
    }
}


    chain POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
                oifname "vmbr0" ip saddr 10.10.10.0/28 counter masquerade comment "Lan"
		        }

    chain PREROUTING {
                type nat hook prerouting priority dstnat; policy accept;

                iifname "vmbr0" tcp dport 80 dnat to 10.10.10.2 comment "OpenVPN tcp"
                iifname "vmbr0" udp dport 49852  dnat to 10.10.10.2 comment "OpenVPN udp"
			}
}

table ip6 filter {
    chain input {
        type filter hook input priority filter; policy drop;
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
    }

    chain output {
        type filter hook output priority filter; policy drop;
    }
}

